name: QA Engineer CI/CD

on:
  push:
    branches: [ qa-engineer ]
  pull_request:
    branches: [ qa-engineer ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java-version: ['17', '21']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean compile --file simplebank/backend/pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java-version: ['17', '21']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn test --file simplebank/backend/pom.xml

  # 2. Security Scans
  security-scans:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java, javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .

  dependency-container-scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs,config'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  dependency-check:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'SimpleBank'
          path: '.'
          format: 'HTML'
